### ISSUE TITLE
Implement (non-) membership proof for an MPT element with a given key

### ISSUE THREAD

**Issue by kushti** [input-output-hk/mantis#350]
For client applications (like light clients) this would be very helpful. There's an implementation of this functionality in Geth.

**Comment by lemastero** [comment]
Thank you @kushti for reporting 🙇 
I am working on exposing getProof using JSON-RPC endpoint as described in [EIP-1186](https://eips.ethereum.org/EIPS/eip-1186). The next step will be exactly non-membership proof.

**Comment by drospa** [comment]
Hello @kushti,

we have a solution for both membership and non membership. They are both merged into development branch, they will be available in our next release.

https://github.com/input-output-hk/mantis/pull/869
https://github.com/input-output-hk/mantis/pull/899

**Comment by dzajkowski** [comment]
Looks done, closing. @kushti thanks for reporting!
