### ISSUE TITLE
mantis.exe: Error invoking method.

### ISSUE THREAD

**Issue by TheCrowbill** [input-output-hk/mantis#374]
Below is my report of errors encountered while installing the **Daedalus Wallet/Mantis Client RC1.**
If there is any further information that would be helpful, please ask. Thank you.

Installation on Windows 10 Home using [daedalus-win64-1.0.3901.0-installer-with-chain.exe](https://github.com/input-output-hk/mantis/releases) in the following steps:

1. Installer launched from Download folder.
2. Installer verification completes.
3. Installer Setup defaults accepted.
![screenshot_20171222211356](https://user-images.githubusercontent.com/19386045/34317175-7a2a3636-e76e-11e7-86fd-428b3b337e25.png)

4. `bootstrap.bat` executes
![screenshot_20171222211614](https://user-images.githubusercontent.com/19386045/34317186-a9a14b5c-e76e-11e7-936a-9ba914367f94.png)

5. `mantis.exe` executes in `CMD` window
![screenshot_20171222211500](https://user-images.githubusercontent.com/19386045/34317220-616ae108-e76f-11e7-897d-777fd1080430.png)

6. Installer output remains at this point for over ten minutes. The system is alive during this time.
![screenshot_20171222224634](https://user-images.githubusercontent.com/19386045/34317226-bed3f9e2-e76f-11e7-83f7-e97d3de8a5d2.png)

7. Error message 1 appears
![screenshot_20171222225045](https://user-images.githubusercontent.com/19386045/34317242-f6bbcfba-e76f-11e7-862d-0842a2b1f705.png)

8. Error message 2 immediately follows dismissing the first error.
![screenshot_20171222225056](https://user-images.githubusercontent.com/19386045/34317248-27f0c9a0-e770-11e7-84c0-1b790ed770f9.png)

9. Installer reports successful installation.
![screenshot_20171222225114](https://user-images.githubusercontent.com/19386045/34317253-3a6bf140-e770-11e7-9005-b45282404f84.png)

10. 'Close' button dismisses Setup window.

Launching `"C:\Program Files\Daedalus Mantis\daedalus.bat" from` the created Start menu icon yields:
![screenshot_20171222233650](https://user-images.githubusercontent.com/19386045/34317297-2b1a45f6-e771-11e7-9b98-46fe1f2c229b.png)

Followed by:
![screenshot_20171222233710](https://user-images.githubusercontent.com/19386045/34317301-53a8c286-e771-11e7-8a42-bf12a0ebad94.png)

The computer remains active, but the Daedalus application window shows no sync progression if syncing is actually happening at all.  Left it in this state for over an hour, no observable change occurs.  There is also no evidence of hard drive access or network activity during this time though connections remain alive. The app window can be closed.

Use of the installed Uninstaller removes Daedalus from the system apparently cleanly.

This error is repeatable.

**Comment by LukasGasior1** [comment]
Hi @TheCrowbill, thank you for reporting the issue.
Unfortunately I was not able to reproduce it on my win 8.1.
Can you please check if there's anything unusual in `.mantis/logs` inside your user home directory or even better share the log here?
Also, just to make sure it's not something with your download, can you check the output of `CertUtil -hashfile daedalus-win64-1.0.3901.0-installer-with-chain.exe MD5` (it should be `5cd6f8b9813cfd2d32b45d8d0c214bdb`)?

**Comment by TheCrowbill** [comment]
5cd6f8b9813cfd2d32b45d8d0c214bdb
CertUtil: -hashfile command completed successfully.

**Comment by TheCrowbill** [comment]
I have encountered the same errors on two Win10 machines. The first was Win10 Home; the latest Win10 Pro. 

Attached is the log file from the latter.


C:\Program Files\Daedalus Mantis>set OUTDIR="C:\Program Files\Daedalus Mantis" 

C:\Program Files\Daedalus Mantis>pwd
'pwd' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Daedalus Mantis>dir
 Volume in drive C is Local Disk
 Volume Serial Number is 3037-024D

 Directory of C:\Program Files\Daedalus Mantis

31-Dec-17  04:27 AM    <DIR>          .
31-Dec-17  04:27 AM    <DIR>          ..
20-Nov-17  05:42 AM           685,432 advapi32.dll
19-Dec-17  07:23 PM            19,136 api-ms-win-core-console-l1-1-0.dll
19-Dec-17  07:23 PM            18,112 api-ms-win-core-datetime-l1-1-0.dll
19-Dec-17  07:23 PM            18,112 api-ms-win-core-debug-l1-1-0.dll
19-Dec-17  07:23 PM            18,624 api-ms-win-core-errorhandling-l1-1-0.dll
19-Dec-17  07:23 PM            22,208 api-ms-win-core-file-l1-1-0.dll
19-Dec-17  07:23 PM            18,624 api-ms-win-core-file-l1-2-0.dll
19-Dec-17  07:23 PM            18,624 api-ms-win-core-file-l2-1-0.dll
19-Dec-17  07:23 PM            18,624 api-ms-win-core-handle-l1-1-0.dll
19-Dec-17  07:23 PM            18,624 api-ms-win-core-heap-l1-1-0.dll
19-Dec-17  07:23 PM            18,624 api-ms-win-core-interlocked-l1-1-0.dll
19-Dec-17  07:23 PM            19,136 api-ms-win-core-libraryloader-l1-1-0.dll
19-Dec-17  07:23 PM            21,184 api-ms-win-core-localization-l1-2-0.dll
19-Dec-17  07:23 PM            19,136 api-ms-win-core-memory-l1-1-0.dll
19-Dec-17  07:23 PM            18,624 api-ms-win-core-namedpipe-l1-1-0.dll
19-Dec-17  07:23 PM            19,648 api-ms-win-core-processenvironment-l1-1-0.dll
19-Dec-17  07:23 PM            20,672 api-ms-win-core-processthreads-l1-1-0.dll
19-Dec-17  07:23 PM            19,136 api-ms-win-core-processthreads-l1-1-1.dll
19-Dec-17  07:23 PM            18,120 api-ms-win-core-profile-l1-1-0.dll
19-Dec-17  07:23 PM            18,624 api-ms-win-core-rtlsupport-l1-1-0.dll
19-Dec-17  07:23 PM            18,624 api-ms-win-core-string-l1-1-0.dll
19-Dec-17  07:23 PM            20,672 api-ms-win-core-synch-l1-1-0.dll
19-Dec-17  07:23 PM            19,136 api-ms-win-core-synch-l1-2-0.dll
19-Dec-17  07:23 PM            19,656 api-ms-win-core-sysinfo-l1-1-0.dll
19-Dec-17  07:23 PM            18,624 api-ms-win-core-timezone-l1-1-0.dll
19-Dec-17  07:23 PM            18,624 api-ms-win-core-util-l1-1-0.dll
20-Nov-17  05:42 AM            11,616 api-ms-win-core-xstate-l2-1-0.dll
19-Dec-17  07:23 PM            19,648 api-ms-win-crt-conio-l1-1-0.dll
19-Dec-17  07:23 PM            22,720 api-ms-win-crt-convert-l1-1-0.dll
19-Dec-17  07:23 PM            19,136 api-ms-win-crt-environment-l1-1-0.dll
19-Dec-17  07:23 PM            20,672 api-ms-win-crt-filesystem-l1-1-0.dll
19-Dec-17  07:23 PM            19,136 api-ms-win-crt-heap-l1-1-0.dll
19-Dec-17  07:23 PM            19,136 api-ms-win-crt-locale-l1-1-0.dll
19-Dec-17  07:23 PM            27,840 api-ms-win-crt-math-l1-1-0.dll
19-Dec-17  07:23 PM            26,304 api-ms-win-crt-multibyte-l1-1-0.dll
19-Dec-17  07:23 PM            70,848 api-ms-win-crt-private-l1-1-0.dll
19-Dec-17  07:23 PM            19,648 api-ms-win-crt-process-l1-1-0.dll
19-Dec-17  07:23 PM            23,232 api-ms-win-crt-runtime-l1-1-0.dll
19-Dec-17  07:23 PM            24,768 api-ms-win-crt-stdio-l1-1-0.dll
19-Dec-17  07:23 PM            24,768 api-ms-win-crt-string-l1-1-0.dll
19-Dec-17  07:23 PM            21,184 api-ms-win-crt-time-l1-1-0.dll
19-Dec-17  07:23 PM            19,136 api-ms-win-crt-utility-l1-1-0.dll
20-Nov-17  05:42 AM            11,616 api-ms-win-eventing-provider-l1-1-0.dll
19-Dec-17  07:23 PM            24,844 blink_image_resources_200_percent.pak
19-Dec-17  07:15 PM               435 build-certificates-win64-mantis.bat
19-Dec-17  07:23 PM                15 content_resources_200_percent.pak
19-Dec-17  07:23 PM        12,016,787 content_shell.pak
19-Dec-17  07:23 PM         4,173,928 d3dcompiler_47.dll
31-Dec-17  04:26 AM               148 daedalus.bat
19-Dec-17  07:23 PM        80,621,056 Daedalus.exe
19-Dec-17  07:23 PM         1,960,448 ffmpeg.dll
19-Dec-17  07:23 PM        10,130,560 icudtl.dat
31-Dec-17  04:26 AM    <DIR>          include
20-Nov-17  05:42 AM         2,088,448 libeay32.dll
19-Dec-17  07:23 PM            17,408 libEGL.dll
20-Nov-17  05:42 AM            83,742 libgcc_s_seh-1.dll
19-Dec-17  07:23 PM         3,429,376 libGLESv2.dll
20-Nov-17  05:42 AM           352,256 libssl32.dll
20-Nov-17  05:42 AM         1,422,981 libstdc++-6.dll
20-Nov-17  05:42 AM            56,978 libwinpthread-1.dll
19-Dec-17  07:23 PM             1,060 LICENSE
19-Dec-17  07:23 PM         1,762,745 LICENSES.chromium.html
31-Dec-17  04:27 AM    <DIR>          locales
19-Dec-17  07:23 PM           633,152 msvcp140.dll
20-Nov-17  05:42 AM           963,232 msvcr120.dll
19-Dec-17  07:23 PM           262,947 natives_blob.bin
19-Dec-17  07:23 PM        18,650,112 node.dll
19-Dec-17  07:23 PM           140,979 pdf_viewer_resources.pak
31-Dec-17  04:27 AM    <DIR>          resources
20-Nov-17  05:42 AM         6,600,704 rocksdb.dll
19-Dec-17  07:23 PM         1,449,400 snapshot_blob.bin
20-Nov-17  05:42 AM           352,256 ssleay32.dll
19-Dec-17  07:23 PM           997,056 ucrtbase.dll
19-Dec-17  07:23 PM            76,195 ui_resources_200_percent.pak
19-Dec-17  07:23 PM            87,888 vcruntime140.dll
19-Dec-17  07:23 PM                 6 version
19-Dec-17  07:29 PM                10 version.txt
19-Dec-17  07:23 PM            57,450 views_resources_200_percent.pak
31-Dec-17  04:26 AM    <DIR>          x64
31-Dec-17  04:26 AM    <DIR>          x86
              75 File(s)    149,980,370 bytes
               7 Dir(s)  31,631,167,488 bytes free

C:\Program Files\Daedalus Mantis>mkdir tls 

C:\Program Files\Daedalus Mantis>mkdir tls\ca 

C:\Program Files\Daedalus Mantis>resources\app\mantis\mantis keytool -genkey -keyalg RSA -alias mantis -keystore conf/mantis.jks -validity 3650 -keysize 2048 -storepass nopassword -keypass nopassword -dname "CN=localhost" 

C:\Program Files\Daedalus Mantis>resources\app\mantis\mantis keytool -keystore conf/mantis.jks -export -alias mantis -file "C:\Program Files\Daedalus Mantis"\tls\ca\ca.der -storepass nopassword 
Certificate stored in file <C:\Program Files\Daedalus Mantis\tls\ca\ca.der>

C:\Program Files\Daedalus Mantis>x64\openssl x509 -in tls\ca\ca.der -inform der -out tls\ca\ca.crt 
WARNING: can't open config file: c:/libressl/ssl/openssl.cnf

**Comment by TheCrowbill** [comment]
@LukasGasior1 Here's a new wrinkle! On the Win10 Pro install, launching Daedalus opens a `cmd` window with:

[05:09:18:0309] [error] EtcApi::getSyncProgress error: {
  "stack": "Error: connect ECONNREFUSED 127.0.0.1:8546\n    at Object.exports._errnoException (util.js:1050:11)\n    at exports._exceptionWithHostPort (util.js:1073:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)",
  "message": "connect ECONNREFUSED 127.0.0.1:8546",
  "code": "ECONNREFUSED",
  "errno": "ECONNREFUSED",
  "syscall": "connect",
  "address": "127.0.0.1",
  "port": 8546
}
[05:09:18:0628] [error] EtcApi::getSyncProgress error: {
  "stack": "Error: connect ECONNREFUSED 127.0.0.1:8546\n    at Object.exports._errnoException (util.js:1050:11)\n    at exports._exceptionWithHostPort (util.js:1073:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)",
  "message": "connect ECONNREFUSED 127.0.0.1:8546",
  "code": "ECONNREFUSED",
  "errno": "ECONNREFUSED",
  "syscall": "connect",
  "address": "127.0.0.1",
  "port": 8546
}

Good luck and thank you!

**Comment by ntallar** [comment]
Hi @TheCrowbill !
I was able to reproduce this issue on my Win 10 machine. After uninstalling the Daedalus wallet, could you try runnning the installer from the `Desktop` folder instead of `Downloads`? That seems to be a temporary fix to this issue on my machine.

**Comment by TheCrowbill** [comment]
Hi @ntallar. The workaround you suggest does not work for my Surface running Win10 Pro. I have not tested on the Win10 Home desktop. Thanks!

**Comment by mcsherrylabs** [comment]
Issue was with window plus bootstrap installer, that binary has been withdrawn as the checksum was using MD5. Furthermore although disappointing that this error occurs, MS Surface is not a supported platform.
