### ISSUE TITLE
The Daedalus-Mantis installation failed.

### ISSUE THREAD

**Issue by tcheeric** [input-output-hk/mantis#379]
I have downloaded the daedalus mantis release and tried to install but the installation failed right at the end.
Here is a screeshot:
https://pbs.twimg.com/media/DSp2sWXX0AAk-rd.jpg

I have noticed a new "icon" on my computer in the form of a question mark.
![image](https://user-images.githubusercontent.com/6341500/34585456-ac07fee4-f197-11e7-88b7-0b3c8c2e0d32.png)

Also, my deadalus is not working anymore. I am now getting the infamous "connecting to network..." issue. Not sure if related though...

**Comment by KonradStaniec** [comment]
Hello @tcheeric , thanks for report!.
I see in the image you have attached that you have `Daedelus for Cardano` instaled and possibly `MacOs`? 
If this is the case, unfortunately, you would need to uninstall it before installing `Daedalus for Mantis`
As for this version  Daedalus Mantis and Daedalus for Cardano, compatibility has not been finalized yet, and you can not have both on one pc.
To repair your current Daedalus installation you should reinstall it.

**Comment by kanr** [comment]
I am having the same issue. Already have Daedalus for Cardano and would like to use both. Is that going to eventually be possible?

**Comment by mirkoAlic** [comment]
We will not provide support for Daedalus wallet any more. But soon there will be news about wallet integration for Mantis.
