### ISSUE TITLE
Error in try to run sbt test

### ISSUE THREAD

**Issue by miniguez31** [input-output-hk/mantis#392]
[error] (*:update) sbt.ResolveException: unresolved dependency: uk.co.josephearl#sbt-verify;0.3.0-SNAPSHOT: not found

**Comment by AlanVerbner** [comment]
Hi @miniguez31, I think `sbt-verify` dependency is missing. Can you please try this steps (taken from https://github.com/input-output-hk/mantis#build-the-client) and then run sbt test again?

> First of all sbt-verify is used in order to check the validity of the downloaded libraries checksums.
>
> sbt-verify can be downloaded from our read only repository by typing
> 
> `git clone https://github.com/input-output-hk/sbt-verify`
> 
> Then in order to make sbt-verify available to our build type
>
> `cd sbt-verify` 
> `sbt publishLocal`

**Comment by miniguez31** [comment]
Thank you  very  much, I will try it

**Comment by AlanVerbner** [comment]
@miniguez31 I'm going to close this issue. If you think the error still persists, don't hesistate to re-open it and leave a comment.

**Comment by miniguez31** [comment]
Hi Alan, I installed sbt-verify and now everything is ok, sorry for the
issue it was my mistake
