### ISSUE TITLE
validateBlocks() returns last block's validate result which may not be the forAll result

### ISSUE THREAD

**Issue by dcaoyuan** [input-output-hk/mantis#396]
https://github.com/input-output-hk/mantis/blob/17d1d44689d705ff0956268b4d36247c414a6f5d/src/main/scala/io/iohk/ethereum/blockchain/sync/SyncBlocksValidator.scala#L24

validateBlocks should collect any Invalid/DbError result of every block, instead only set result to the result of last block.

BTW, the forAll result (which returns a Boolean) is never used in the context.

**Comment by LukasGasior1** [comment]
I think forAll here is used to stop further validation when first error occurs (and yes, its result is not used). With that, `result` is either `Valid` (no error) or first encountered error. I must admit though, it's not that straightforward to see this logic there.

**Comment by rtkaczyk** [comment]
> it's not that straightforward to see this logic there

We may consider a refactoring or at least adding an explanation comment. 
(On first inspection I thought @dcaoyuan was right. I guess when we see `forAll` we think "for *all*", without considering it only needs to evaluate to the first `false`)

**Comment by dcaoyuan** [comment]
@rtkaczyk yeah, I almost forgot that `forall` will break out when evaluated the first `false`.

I agree that the current code works, although not so straightforward.
