### ISSUE TITLE
Should calcStartGas before memory.load(...)

### ISSUE THREAD

**Issue by dcaoyuan** [input-output-hk/mantis#398]
Since Memory.load(...) will automatically expanded to needed size:
https://github.com/input-output-hk/mantis/blob/17d1d44689d705ff0956268b4d36247c414a6f5d/src/main/scala/io/iohk/ethereum/vm/Memory.scala#L60-L73

The memory.load(...) here 
https://github.com/input-output-hk/mantis/blob/17d1d44689d705ff0956268b4d36247c414a6f5d/src/main/scala/io/iohk/ethereum/vm/OpCode.scala#L761-L764

May have extended memory size to (inOffset + inSize), which may cause potential wrong calcMemCost(...) result when decide by:

https://github.com/input-output-hk/mantis/blob/17d1d44689d705ff0956268b4d36247c414a6f5d/src/main/scala/io/iohk/ethereum/vm/EvmConfig.scala#L102

in

**Comment by rtkaczyk** [comment]
I'm not sure I understand you, you may want to rephrase or grammar-proof your question. At any rate, I don't see anything wrong with the referenced code. Could it be you have missed the fact that `Memory` is immutable?

**Comment by dcaoyuan** [comment]
Oh yes, I missed that memory is immutable. I'm porting Mantis to ETH, and for performance reason, I've done some 'immutable' to 'mutable' changes, `Memory` is one of them, thus I encountered the mentioned issue at ETH's block #4939345

The porting code is now a big difference from the original Mantis, I should report issues for Mantis more carefully now.

**Comment by rtkaczyk** [comment]
@dcaoyuan Interesting! We do have support for ETH, but not yet for Byzantium/Constantinople forks, and currently no plans for that as far as I know.

I'm curious, what kind of performance boost did you achieve when going from immutable to mutable structures?

Anyway, thanks for the interest in the project.

**Comment by dcaoyuan** [comment]
I've passed Byzantium fork, now encountered performance issue with tx increasing so much after Dec 2017.

I changed Memory/Stack from immutable to mutable to reduce the instances creation, and most fields (except world state) in ProgramState as `var` instead of `val`.

Another easy part is mark all case class to `final` to let the compiler trying to optimize them.

I'll release the source code by the end of Feb.

**Comment by dcaoyuan** [comment]
Another change was that I rewrote the TCP service to akka-stream based and added cache for node storage etc.

**Comment by rtkaczyk** [comment]
> I'll release the source code by the end of Feb.

Awesome. We'll be on the lookout for that. Good luck!

**Comment by dcaoyuan** [comment]
@rtkaczyk as promised, here it is: [https://github.com/khipu-io/khipu](https://github.com/khipu-io/khipu)
