### ISSUE TITLE
ECIP 1041 - Remove Difficulty Bomb

### ISSUE THREAD

**Issue by pyskell** [input-output-hk/mantis#415]
Enable difficulty bomb defusion at block:

* 5900000 on Ethereum Classic mainnet,
* 2300000 on morden testnet.

Reference:
https://github.com/ethereumproject/ECIPs/blob/master/ECIPs/ECIP-1041.md

See references for other clients here:
https://github.com/paritytech/parity/pull/7905
https://github.com/ethereumproject/go-ethereum/releases/tag/v5.0.0

**Comment by AlanVerbner** [comment]
Done by @KonradStaniec in https://github.com/input-output-hk/mantis/pull/417
