### ISSUE TITLE
Broken SBT build

### ISSUE THREAD

**Issue by arukavytsia** [input-output-hk/mantis#419]
Can't build the project with SBT in interactive mode, because of broken dependency:
`sbt.ResolveException: unresolved dependency: uk.co.josephearl#sbt-verify;0.3.0-SNAPSHOT: not found`.

**Comment by AlanVerbner** [comment]
Hi @arukavytsia, can you please check the fix suggested in https://github.com/input-output-hk/mantis/issues/392#issuecomment-360647519 and let us know?

Thanks!

**Comment by arukavytsia** [comment]
@AlanVerbner It helped indeed
