### ISSUE TITLE
Parser was blocked due to document.write

### ISSUE THREAD

**Issue by ss77ss** [input-output-hk/mantis#423]
Syncing blocks stays at 0.00% and when I go to developer tools it shows:
```
index.html:11 [Violation] Avoid using document.write().
index.html:32 [Violation] Avoid using document.write().
2index.html:32 [Violation] Parser was blocked due to document.write(<script>)
```
Might be separate issue:
About screen shows 0.8.3 as the version (assuming that is version number in there) but the title bar of the application shows version as 1.0.4091.

Downloaded from https://github.com/input-output-hk/mantis/releases.
Issue is on MacOS High Sierra.

**Comment by mirkoAlic** [comment]
2 years without a response. Sorry about that! I'm goint to close this, given we are rebooting the project and we want a fresh start. Feel free of open the issue again if you re-try with latest versions and the issue persisted.
