### ISSUE TITLE
transactions doesn't get mined

### ISSUE THREAD

**Issue by RamiroMoreira** [input-output-hk/mantis#481]
hello, i just tried this guide:
https://medium.com/emurgohk/how-to-get-on-the-cardano-kevm-testnet-835009fa2c8d

i don't know if this is the place to ask, but the transactions never get mined, when i check the getReceipt(txID) i get “receipt not available”.
I tried it with a lot of gas and high prices and value, also with the sugested in the guide, didn't work.

maybe it is something related to the error i get when i run ./bin/mantis&

"Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'environment'"

after that exeption it keeps printing:
UDP server not running. Not sending ping message.

I would appreciate some help.

**Comment by nomelc** [comment]
Check #483, I just posted my solution to this error there. Mantis does not return any error if the sendTransaction parameters are wrong e.g. too little gas provided to mine the transaction returns a tx but you will never get a receipt. It worked for me with these parameters:
```
sendTransaction(to = receiverAddress, gas = 5000000, gasPrice = 5000000000, value = 123456, data = "simple value transfer")
```

**Comment by mirkoAlic** [comment]
No longer KEVM support is provided.
