### ISSUE TITLE
application.conf missing from mantis_iele-testnet_v0.1.zip / mantis-1.0-daedalus-rc1

### ISSUE THREAD

**Issue by drandreaskrueger** [input-output-hk/mantis#503]
> The mantis.consensus key that resides in the application.conf file is used for consensus-related configuration.  
> http://testnet.iohkdev.io/goguen/testnet/get-started/implementing-the-raft-consensus-protocol/

but there is no `application.conf` in `mantis_iele-testnet_v0.1.zip` / `mantis-1.0-daedalus-rc1` 

from 

https://github.com/input-output-hk/mantis/releases/download/iele_testnet_v0.1/mantis_iele-testnet_v0.1.zip

**Comment by mirkoAlic** [comment]
Sorry, there is no longer support for `mantis_iele-testnet` neither daedalus wallet integration.

**Comment by drandreaskrueger** [comment]
lol
