### ISSUE TITLE
include a README into mantis_iele-testnet_v0.1.zip

### ISSUE THREAD

**Issue by drandreaskrueger** [input-output-hk/mantis#504]
imagine someone who has never used your system. what about providing some instructions?

regardless what I tried with the stuff provided in mantis_iele-testnet_v0.1.zip ... I always got some error message.

so ... it is not self-explanatory.

-->

perhaps simply include a link to https://github.com/input-output-hk/mantis/wiki/Mallet

into https://github.com/input-output-hk/mantis/releases/download/iele_testnet_v0.1/mantis_iele-testnet_v0.1.zip

?

**Comment by mirkoAlic** [comment]
Sorry, there is no longer support to `mantis_iele-testnet`.
