### ISSUE TITLE
Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'environment'

### ISSUE THREAD

**Issue by NOCTLJRNE** [input-output-hk/mantis#636]
Hi, I tried to launch the mantis client, but still got this issue , I've read all the issues thread in the past and thought this was already fixed ? 
Thanks for the support in advance.
![issue1](https://user-images.githubusercontent.com/13896688/54198115-f91a3080-44c5-11e9-917b-6adc6fa3ce33.JPG)

**Comment by mirkoAlic** [comment]
Too old. @NOCTLJRNE if you are still interest, please check latest `develop` branch, or re-open the issue. Sorry the lack of response. This project was dead for a long period of time, but now it was rebooted.
