### ISSUE TITLE
Derivation of daedalus mantis need?

### ISSUE THREAD

**Issue by Frddyfox** [input-output-hk/mantis#640]
Hello my wallet doesnt sync. So i tried to import it to Classic Ether wallet. There is obviously not the right derivation for my recouvery phrase. Please help!

**Comment by rdlrt** [comment]
Worked with the user on telegram. To access the wallet from CEW/MEW , need to use keystore file option. The keystore file from mantis is located in %userprofile%\.mantis\keystore folder. Once selecting the file, enter the passphrase and unlock.
